### ISSUE TITLE
Does it require adb executable?

### ISSUE THREAD

**Issue by sharpordie** [patagonaa/AdbClient.NET#1]
Does it require adb executable and if so did you try using it with MAUI for Android or iOS applications?

**Comment by patagonaa** [comment]
It does need an installed ADB executable and a running ADB server (the server isn't started automatically). I haven't tried/installed MAUI, but if it comes with Android support it probably installs the Android Platform Tools which include ADB.

But at least Android SDK doesn't seem to add the ADB executable to the `PATH` variable, so you'll have to either add that or use the full path.

So if it is in `PATH` (you can check by opening a command line and typing `adb version`, if that shows the version it is in `PATH`) you can use
```csharp
await Process.Start("adb", "start-server").WaitForExitAsync();
```
to your code to start the ADB server before initializing the ADB client, otherwise you'll have to use something like
```csharp
await Process.Start(@"C:\Program Files\[...]\platform-tools\adb.exe", "start-server").WaitForExitAsync();
```

If installed via Android Studio, the path should be something like `C:\Users\<username>\AppData\Local\Android\Sdk\platform-tools\adb.exe`

**Comment by sharpordie** [comment]
Thank you for your reply.
